# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c190141ca1d18eb9e16820144e7639349ca2cbfeda2984fcb8f63794ac44ed8bfc43caaaef4ef1f3d6742e2d97f34a46d989e4f4c8c44cf2a879bc30b35cc8c

test:
  secret_key_base: ea4394000f080bf8f07edd729378dc5faaa3c69e34bea134bcd8bf0d2091eae60f442e8b3115b28539f2f3c67c84f19d72bbd825ab56f5c6ebe76d0f04d3007e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
